[project]
name = "ita-personalization-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "pandas>=3.0.5",
    "prometheus-fastapi-instrumentator>=8.1.0",
    "pytest>=9.1.1",
    "scikit-learn>=1.9.0",
    "structlog>=26.1.0",
    "uvicorn>=0.52.1",
]

[project.scripts]
ita-personalization-service = "ita_personalization_service:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
